/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CustomRouter } from "./CustomRouter";
export type { CustomRouterSchemaHook } from "./CustomRouterSchemaHook";
