/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface CustomRouterWithAttesterInterface extends utils.Interface {
  functions: {
    "acceptOwnership()": FunctionFragment;
    "controller()": FunctionFragment;
    "controllerChainSelector()": FunctionFragment;
    "controllerVault()": FunctionFragment;
    "depositToFeeTank(uint256)": FunctionFragment;
    "feeTank(address)": FunctionFragment;
    "generateKey(bytes32,uint256,uint256,uint256)": FunctionFragment;
    "linkToken()": FunctionFragment;
    "messageIdToTokenAmount(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "quoteCrossChainMessage(uint64,uint256,bool,uint256)": FunctionFragment;
    "registerAdmin(address)": FunctionFragment;
    "router()": FunctionFragment;
    "routerAdmins(address)": FunctionFragment;
    "setController(address)": FunctionFragment;
    "setControllerChainSelector(uint64)": FunctionFragment;
    "setControllerVault(address)": FunctionFragment;
    "submitReceipt(bytes32,bytes32,uint256,uint256)": FunctionFragment;
    "token()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawFromFeeTank(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOwnership"
      | "controller"
      | "controllerChainSelector"
      | "controllerVault"
      | "depositToFeeTank"
      | "feeTank"
      | "generateKey"
      | "linkToken"
      | "messageIdToTokenAmount"
      | "owner"
      | "quoteCrossChainMessage"
      | "registerAdmin"
      | "router"
      | "routerAdmins"
      | "setController"
      | "setControllerChainSelector"
      | "setControllerVault"
      | "submitReceipt"
      | "token"
      | "transferOwnership"
      | "withdrawFromFeeTank"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "controller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "controllerChainSelector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "controllerVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositToFeeTank",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeTank", values: [string]): string;
  encodeFunctionData(
    functionFragment: "generateKey",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "linkToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "messageIdToTokenAmount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteCrossChainMessage",
    values: [BigNumberish, BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAdmin",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "routerAdmins",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setControllerChainSelector",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setControllerVault",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReceipt",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromFeeTank",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "controllerChainSelector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllerVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToFeeTank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeTank", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "generateKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "linkToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageIdToTokenAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteCrossChainMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "routerAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setControllerChainSelector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setControllerVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromFeeTank",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferRequested(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ReceiptProcessed(bytes32,bytes32,uint256)": EventFragment;
    "RequestProcessed(bytes32,uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceiptProcessed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestProcessed"): EventFragment;
}

export interface OwnershipTransferRequestedEventObject {
  from: string;
  to: string;
}
export type OwnershipTransferRequestedEvent = TypedEvent<
  [string, string],
  OwnershipTransferRequestedEventObject
>;

export type OwnershipTransferRequestedEventFilter =
  TypedEventFilter<OwnershipTransferRequestedEvent>;

export interface OwnershipTransferredEventObject {
  from: string;
  to: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ReceiptProcessedEventObject {
  receiptMessageId: string;
  idempotencyKey: string;
  usedTokens: BigNumber;
}
export type ReceiptProcessedEvent = TypedEvent<
  [string, string, BigNumber],
  ReceiptProcessedEventObject
>;

export type ReceiptProcessedEventFilter =
  TypedEventFilter<ReceiptProcessedEvent>;

export interface RequestProcessedEventObject {
  messageId: string;
  payFeesIn: number;
}
export type RequestProcessedEvent = TypedEvent<
  [string, number],
  RequestProcessedEventObject
>;

export type RequestProcessedEventFilter =
  TypedEventFilter<RequestProcessedEvent>;

export interface CustomRouterWithAttester extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CustomRouterWithAttesterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    controller(overrides?: CallOverrides): Promise<[string]>;

    controllerChainSelector(overrides?: CallOverrides): Promise<[BigNumber]>;

    controllerVault(overrides?: CallOverrides): Promise<[string]>;

    depositToFeeTank(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    feeTank(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    generateKey(
      requestHash: BytesLike,
      fixedNonce: BigNumberish,
      operationType: BigNumberish,
      payFeesIn: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    linkToken(overrides?: CallOverrides): Promise<[string]>;

    messageIdToTokenAmount(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    quoteCrossChainMessage(
      targetChain: BigNumberish,
      payFeesIn: BigNumberish,
      includeToken: boolean,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { cost: BigNumber }>;

    registerAdmin(
      admin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    router(overrides?: CallOverrides): Promise<[string]>;

    routerAdmins(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    setController(
      _controller: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setControllerChainSelector(
      _controllerChainSelector: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setControllerVault(
      _controllerVault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    submitReceipt(
      reqeustMessageId: BytesLike,
      idempotencyKey: BytesLike,
      usedTokens: BigNumberish,
      payFeesIn: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawFromFeeTank(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  acceptOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  controller(overrides?: CallOverrides): Promise<string>;

  controllerChainSelector(overrides?: CallOverrides): Promise<BigNumber>;

  controllerVault(overrides?: CallOverrides): Promise<string>;

  depositToFeeTank(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  feeTank(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  generateKey(
    requestHash: BytesLike,
    fixedNonce: BigNumberish,
    operationType: BigNumberish,
    payFeesIn: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  linkToken(overrides?: CallOverrides): Promise<string>;

  messageIdToTokenAmount(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  quoteCrossChainMessage(
    targetChain: BigNumberish,
    payFeesIn: BigNumberish,
    includeToken: boolean,
    tokenAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  registerAdmin(
    admin: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  router(overrides?: CallOverrides): Promise<string>;

  routerAdmins(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  setController(
    _controller: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setControllerChainSelector(
    _controllerChainSelector: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setControllerVault(
    _controllerVault: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  submitReceipt(
    reqeustMessageId: BytesLike,
    idempotencyKey: BytesLike,
    usedTokens: BigNumberish,
    payFeesIn: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawFromFeeTank(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    controller(overrides?: CallOverrides): Promise<string>;

    controllerChainSelector(overrides?: CallOverrides): Promise<BigNumber>;

    controllerVault(overrides?: CallOverrides): Promise<string>;

    depositToFeeTank(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    feeTank(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    generateKey(
      requestHash: BytesLike,
      fixedNonce: BigNumberish,
      operationType: BigNumberish,
      payFeesIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    linkToken(overrides?: CallOverrides): Promise<string>;

    messageIdToTokenAmount(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    quoteCrossChainMessage(
      targetChain: BigNumberish,
      payFeesIn: BigNumberish,
      includeToken: boolean,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerAdmin(admin: string, overrides?: CallOverrides): Promise<void>;

    router(overrides?: CallOverrides): Promise<string>;

    routerAdmins(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    setController(
      _controller: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setControllerChainSelector(
      _controllerChainSelector: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setControllerVault(
      _controllerVault: string,
      overrides?: CallOverrides
    ): Promise<void>;

    submitReceipt(
      reqeustMessageId: BytesLike,
      idempotencyKey: BytesLike,
      usedTokens: BigNumberish,
      payFeesIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;

    transferOwnership(to: string, overrides?: CallOverrides): Promise<void>;

    withdrawFromFeeTank(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferRequested(address,address)"(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferRequestedEventFilter;
    OwnershipTransferRequested(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferRequestedEventFilter;

    "OwnershipTransferred(address,address)"(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferredEventFilter;

    "ReceiptProcessed(bytes32,bytes32,uint256)"(
      receiptMessageId?: BytesLike | null,
      idempotencyKey?: BytesLike | null,
      usedTokens?: null
    ): ReceiptProcessedEventFilter;
    ReceiptProcessed(
      receiptMessageId?: BytesLike | null,
      idempotencyKey?: BytesLike | null,
      usedTokens?: null
    ): ReceiptProcessedEventFilter;

    "RequestProcessed(bytes32,uint8)"(
      messageId?: BytesLike | null,
      payFeesIn?: null
    ): RequestProcessedEventFilter;
    RequestProcessed(
      messageId?: BytesLike | null,
      payFeesIn?: null
    ): RequestProcessedEventFilter;
  };

  estimateGas: {
    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    controller(overrides?: CallOverrides): Promise<BigNumber>;

    controllerChainSelector(overrides?: CallOverrides): Promise<BigNumber>;

    controllerVault(overrides?: CallOverrides): Promise<BigNumber>;

    depositToFeeTank(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    feeTank(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    generateKey(
      requestHash: BytesLike,
      fixedNonce: BigNumberish,
      operationType: BigNumberish,
      payFeesIn: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    linkToken(overrides?: CallOverrides): Promise<BigNumber>;

    messageIdToTokenAmount(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    quoteCrossChainMessage(
      targetChain: BigNumberish,
      payFeesIn: BigNumberish,
      includeToken: boolean,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerAdmin(
      admin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    router(overrides?: CallOverrides): Promise<BigNumber>;

    routerAdmins(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    setController(
      _controller: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setControllerChainSelector(
      _controllerChainSelector: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setControllerVault(
      _controllerVault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    submitReceipt(
      reqeustMessageId: BytesLike,
      idempotencyKey: BytesLike,
      usedTokens: BigNumberish,
      payFeesIn: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawFromFeeTank(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    controller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    controllerChainSelector(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    controllerVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositToFeeTank(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    feeTank(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    generateKey(
      requestHash: BytesLike,
      fixedNonce: BigNumberish,
      operationType: BigNumberish,
      payFeesIn: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    linkToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    messageIdToTokenAmount(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteCrossChainMessage(
      targetChain: BigNumberish,
      payFeesIn: BigNumberish,
      includeToken: boolean,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerAdmin(
      admin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    routerAdmins(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setController(
      _controller: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setControllerChainSelector(
      _controllerChainSelector: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setControllerVault(
      _controllerVault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    submitReceipt(
      reqeustMessageId: BytesLike,
      idempotencyKey: BytesLike,
      usedTokens: BigNumberish,
      payFeesIn: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawFromFeeTank(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
